{{- if .Values.beads3d.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gasboat.beads3d.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gasboat.beads3d.labels" . | nindent 4 }}
spec:
  type: {{ .Values.beads3d.service.type }}
  ports:
    - port: {{ .Values.beads3d.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gasboat.beads3d.selectorLabels" . | nindent 4 }}
{{- end }}
