apiVersion: v2
name: gasboat
description: Gasboat â€” K8s agent controller, coopmux, pgbeads and nats events
version: 2026.58.8
appVersion: "2026.58.8"
type: application
keywords:
  - gasboat
  - beads
  - agents
  - coopmux
maintainers:
  - name: Gasboat
    email: devops@gasboat.dev
