{{- if and .Values.agents.enabled .Values.agents.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gasboat.agents.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gasboat.agents.labels" . | nindent 4 }}
  {{- with .Values.agents.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
